// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWobaAWXUqv7Owkuc20GQOwMm4G682n64',
    appId: '1:527346009950:web:0001529ddf94c5aa0ef1cf',
    messagingSenderId: '527346009950',
    projectId: 'education-app-5b9fc',
    authDomain: 'education-app-5b9fc.firebaseapp.com',
    storageBucket: 'education-app-5b9fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANsEx2Qxu_KXjp9OVOzoTafEM7MQclop8',
    appId: '1:527346009950:android:f727f5f8fd53b24f0ef1cf',
    messagingSenderId: '527346009950',
    projectId: 'education-app-5b9fc',
    storageBucket: 'education-app-5b9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1CN6BIlxPNg934LO3d-woWjRYviw1_As',
    appId: '1:527346009950:ios:9fd83d80d2796c150ef1cf',
    messagingSenderId: '527346009950',
    projectId: 'education-app-5b9fc',
    storageBucket: 'education-app-5b9fc.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1CN6BIlxPNg934LO3d-woWjRYviw1_As',
    appId: '1:527346009950:ios:9fd83d80d2796c150ef1cf',
    messagingSenderId: '527346009950',
    projectId: 'education-app-5b9fc',
    storageBucket: 'education-app-5b9fc.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWobaAWXUqv7Owkuc20GQOwMm4G682n64',
    appId: '1:527346009950:web:5c55d33c91ea2c740ef1cf',
    messagingSenderId: '527346009950',
    projectId: 'education-app-5b9fc',
    authDomain: 'education-app-5b9fc.firebaseapp.com',
    storageBucket: 'education-app-5b9fc.firebasestorage.app',
  );
}
